name: MCP Plugins PyPI Publishing

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Install development dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build Agent Toolkit plugin
        run: make dist-plugin PLUGINFOLDER=plugins/agents/agent-toolkit

      - name: Build Model client plugin
        run: make dist-plugin PLUGINFOLDER=plugins/agents/model-client

      - name: Build MCP server plugin
        run: make dist-plugin PLUGINFOLDER=plugins/mcp/mcp-server

      - name: Build MCP client plugin
        run: make dist-plugin PLUGINFOLDER=plugins/mcp/mcp-client

      - name: Publish Agent Toolkit plugin to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish-plugin-pypi PLUGINFOLDER=plugins/agents/agent-toolkit

      - name: Publish Model Client plugin to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish-plugin-pypi PLUGINFOLDER=plugins/agents/model-client

      - name: Publish MCP server plugin to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish-plugin-pypi PLUGINFOLDER=plugins/mcp/mcp-server

      - name: Publish MCP client plugin to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish-plugin-pypi PLUGINFOLDER=plugins/mcp/mcp-client
