# This workflow will install hopeit.engine dev Python dependencies, run tests in multiple version of Python

name: hopeit.agents CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - dev

jobs:
  ci-checks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ["lint", "test"]
        python-version: ["3.12", "3.11", "3.13"]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    
    - name: install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: make ci-deps
      run: PYTHONVERSION=${{ matrix.python-version }} make env

    - name: ${{ matrix.stage }}
      run: |
        make ${{ matrix.stage }}
